export const data = [
  {
    id: 1,
    type: "FOOD",
    description: "Food for the homeless",
    tags: ["CANNED", "FRESH"],
    quantity: 1,
  },
  {
    id: 2,
    type: "CLOTHING",
    description: "Clothing for children",
    tags: ["SMALL", "UNISEX", "WINTER"],
    quantity: 1,
  },
  {
    id: 3,
    type: "TOYS",
    description: "Toys for children",
    tags: ["CARS", "WOODEN", "GOOD QUALITY"],
    quantity: 1,
  },
  {
    id: 3,
    type: "BLOOD_DONATION",
    description: "Blood donation for urgent cases",
    tags: ["BLOOD_TYPE_A", "CAIRO", "AIN SHAMS"],
    quantity: 4,
  },
  {
    id: 4,
    type: "MEDICAL_SUPPLIES",
    description: "Medical supplies like pain relief medication",
    tags: ["PANADOL"],
    quantity: 20,
  },
  {
    id: 5,
    type: "SCHOOL_SUPPLIES",
    description: "School supplies for aspiring children in need",
    tags: ["BOOKS", "NOTEBOOKS", "PENCILS"],
    quantity: 1,
  },
  {
    id: 6,
    type: "CLOTHING",
    description: "Clothing for people in africa",
    tags: ["UNISEX", "ADULT", "CHILDREN", "SUMMER"],
    quantity: 133,
  },
  {
    id: 7,
    type: "BLOOD_DONATION",
    description: "Blood donation",
    tags: ["BLOOD_TYPE_AB", "ALEXANDRIA", "CAIRO"],
    quantity: 1,
  },
  {
    id: 8,
    type: "TOYS",
    description: "Toys for an orphanage",
    tags: ["CARS", "ACTION FIGURES", "DOLLS"],
    quantity: 40,
  },
  {
    id: 9,
    type: "MEDICAL_SUPPLIES",
    description: "Medication for a cancer patient",
    tags: ["CANCER", "CHEMO"],
    quantity: 23,
  },
  {
    id: 10,
    type: "SCHOOL_SUPPLIES",
    description: "Books for students in grade school",
    tags: ["GRADE_SCHOOL", "BOOKS", "MATH"],
    quantity: 23,
  },
  {
    id: 11,
    type: "FOOD",
    description: "Food for refugees",
    tags: ["BREAD"],
    quantity: 122,
  },
  {
    id: 12,
    type: "FOOD",
    description: "Food for families affected by natural disaster",
    tags: ["CANNED", "NON_PERISHABLE"],
    quantity: 1,
  },
  {
    id: 13,
    type: "CLOTHING",
    description: "Winter coats for homeless individuals",
    tags: ["LARGE", "XL", "WATERPROOF"],
    quantity: 20,
  },
  {
    id: 14,
    type: "TOYS",
    description: "Educational toys for children's hospital",
    tags: ["PUZZLES", "GAMES", "BOOKS"],
    quantity: 1,
  },
  {
    id: 15,
    type: "BLOOD_DONATION",
    description: "Blood donation for patients with rare blood type",
    tags: ["BLOOD_TYPE_B-", "RARE", "ANY_LOCATION"],
    quantity: 1,
  },
  {
    id: 16,
    type: "MEDICAL_SUPPLIES",
    description: "Diabetic supplies for low-income individuals",
    tags: ["INSULIN", "TEST_STRIPS"],
    quantity: 1,
  },
  {
    id: 17,
    type: "SCHOOL_SUPPLIES",
    description: "Art supplies for underfunded elementary school",
    tags: ["CRAYONS", "MARKERS", "PAPER"],
    quantity: 1,
  },
  {
    id: 18,
    type: "FOOD",
    description: "Hot meals for soup kitchen",
    tags: ["SOUP", "SANDWICHES", "DRINKS"],
    quantity: 50,
  },
  {
    id: 19,
    type: "BLOOD_DONATION",
    description: "Blood donation for surgery patients",
    tags: ["BLOOD_TYPE_O+", "URGENT", "CAIRO"],
    quantity: 2,
  },
  {
    id: 20,
    type: "TOYS",
    description: "Sports equipment for youth center",
    tags: ["BASKETBALLS", "SOCCER_BALLS", "BASEBALL_GLOVES"],
    quantity: 1,
  },
  {
    id: 21,
    type: "MEDICAL_SUPPLIES",
    description: "First aid kits for disaster relief efforts",
    tags: ["BANDAGES", "ANTISEPTIC", "GAUZE"],
    quantity: 10,
  },
  {
    id: 22,
    type: "CLOTHING",
    description: "Professional attire for job interviews",
    tags: ["SUITS", "DRESSES", "MEDIUM"],
    quantity: 15,
  },
  {
    id: 23,
    type: "FOOD",
    description: "Fresh produce for senior center",
    tags: ["FRUITS", "VEGETABLES", "ORGANIC"],
    quantity: 1,
  },
  {
    id: 24,
    type: "TOYS",
    description: "Musical instruments for children's music therapy",
    tags: ["DRUMS", "GUITARS", "KEYBOARDS"],
    quantity: 5,
  },
  {
    id: 25,
    type: "BLOOD_DONATION",
    description: "Blood donation for sickle cell patients",
    tags: ["SICKLE_CELL", "ANY_BLOOD_TYPE", "CAIRO"],
    quantity: 4,
  },
  {
    id: 26,
    type: "MEDICAL_SUPPLIES",
    description: "Mobility aids for elderly with limited mobility",
    tags: ["WALKERS", "WHEELCHAIRS", "CANES"],
    quantity: 3,
  },
  {
    id: 27,
    type: "SCHOOL_SUPPLIES",
    description: "Science kits for high school students",
    tags: ["CHEMISTRY", "BIOLOGY", "PHYSICS"],
    quantity: 10,
  },
  {
    id: 28,
    type: "FOOD",
    description: "Baby formula for families in need",
    tags: ["INFANT", "FORMULA", "HYPOALLERGENIC"],
    quantity: 20,
  },
  {
    id: 29,
    type: "BLOOD_DONATION",
    description: "Blood donation for trauma center",
    tags: ["ALL_BLOOD_TYPES", "URGENT", "ALEXANDRIA"],
    quantity: 5,
  },
  {
    id: 30,
    type: "TOYS",
    description: "Board games for family shelter",
    tags: ["FAMILY", "FUN", "ALL_AGES"],
    quantity: 1,
  },
  {
    id: 31,
    type: "MEDICAL_SUPPLIES",
    description: "Mental health resources for veterans",
    tags: ["THERAPY", "COUNSELING", "SUPPORT_GROUPS"],
    quantity: 1,
  },
];
