export const data = [
  {
    id: 1,
    description: "Other superficial bite of hand",
    type: "MEDICAL_SUPPLIES",
    location: "Guoyuan",
    tags: ["MEDIUM"],
    quantity: 80,
  },
  {
    id: 2,
    description: "Obstructed labor due to oth malposition and malpresent, unsp",
    type: "SCHOOL_SUPPLIES",
    location: "Barrhead",
    tags: ["SMALL", "ADULT", "TYPE_A", "FRESH"],
    quantity: 52,
  },
  {
    id: 3,
    description: "Varicos vn unsp low extrm w ulc oth prt low extrm and inflam",
    type: "CLOTHING",
    location: "Limoeiro do Norte",
    tags: ["FEMALE", "MEDICAL"],
    quantity: 85,
  },
  {
    id: 4,
    description: "Oth fx lower end of l tibia, subs for clos fx w routn heal",
    type: "MEDICAL_SUPPLIES",
    location: "Qārah",
    tags: ["SMALL", "MEDIUM"],
    quantity: 32,
  },
  {
    id: 5,
    description: "Toxic effect of venom of other African and Asian snake",
    type: "BLOOD_DONATION",
    location: "Bolengpulau",
    tags: ["SMALL", "MEDICAL"],
    quantity: 46,
  },
  {
    id: 6,
    description: "Corros second degree of single finger (nail) except thumb",
    type: "PROBONO",
    location: "Fort McMurray",
    tags: ["LARGE", "WINTER", "CANNED"],
    quantity: 64,
  },
  {
    id: 7,
    description: "Drown due to falling or jumping from crushed canoe or kayak",
    type: "BLOOD_DONATION",
    location: "Rybnoye",
    tags: ["MEDIUM", "FRESH", "CANNED", "XLARGE"],
    quantity: 3,
  },
  {
    id: 8,
    description: "Rheumatoid bursitis, right ankle and foot",
    type: "MEDICAL_SUPPLIES",
    location: "Naawan",
    tags: ["FEMALE", "PAIN_RELIEF", "WINTER", "ADULT"],
    quantity: 49,
  },
  {
    id: 9,
    description: "Exposure to bed fire due to unsp burning material, init",
    type: "CLOTHING",
    location: "Casal das Figueiras",
    tags: ["TYPE_A", "LARGE", "MEDIUM"],
    quantity: 36,
  },
  {
    id: 10,
    description: "Major lacerat great saph at hip and thi lev, right leg, sqla",
    type: "PROBONO",
    location: "Łomazy",
    tags: ["FRESH", "PAIN_RELIEF", "MALE", "TYPE_B"],
    quantity: 65,
  },
  {
    id: 11,
    description: "Assault by antipersonnel bomb, sequela",
    type: "PROBONO",
    location: "Boulaouane",
    tags: ["TYPE_A", "ADULT", "MEDICAL", "SUMMER"],
    quantity: 8,
  },
  {
    id: 12,
    description: "Fall (on) (from) unspecified stairs and steps, subs encntr",
    type: "MEDICAL_SUPPLIES",
    location: "Mouquim",
    tags: ["FEMALE"],
    quantity: 68,
  },
  {
    id: 13,
    description: "Inj intrinsic musc/fasc/tend left ring finger at wrs/hnd lv",
    type: "CLOTHING",
    location: "Purworejo",
    tags: ["TYPE_B", "FRESH", "MEDICAL"],
    quantity: 5,
  },
  {
    id: 14,
    description: "Asphyx d/t mech threat to breathe d/t oth cause, undet, init",
    type: "PROBONO",
    location: "Baicun",
    tags: ["MALE", "XLARGE", "SUMMER"],
    quantity: 33,
  },
  {
    id: 15,
    description: "Anterior cord syndrome at C4, init",
    type: "PROBONO",
    location: "Nymburk",
    tags: ["TYPE_A", "MEDICAL"],
    quantity: 18,
  },
  {
    id: 16,
    description: "Partial placenta previa NOS or without hemor, third tri",
    type: "MEDICAL_SUPPLIES",
    location: "Néa Kíos",
    tags: ["MEDICAL", "ADULT"],
    quantity: 89,
  },
  {
    id: 17,
    description: "Oth physl fx upper end unsp tibia, subs for fx w delay heal",
    type: "FOOD",
    location: "Resende",
    tags: ["TYPE_B", "TYPE_A", "MEDICAL", "LARGE"],
    quantity: 36,
  },
  {
    id: 18,
    description: "Other superficial bite of lip",
    type: "FOOD",
    location: "Bolnisi",
    tags: ["FRESH"],
    quantity: 75,
  },
  {
    id: 19,
    description: "Pathological fracture in neoplastic disease, unsp hand",
    type: "CLOTHING",
    location: "Rongxing",
    tags: ["ADULT", "FEMALE", "FRESH"],
    quantity: 66,
  },
  {
    id: 20,
    description: "Prolonged first stage (of labor)",
    type: "MEDICAL_SUPPLIES",
    location: "Pylaía",
    tags: ["TYPE_A", "SUMMER"],
    quantity: 89,
  },
  {
    id: 21,
    description: "War op w unsp fire/conflagr/hot subst, civilian, init",
    type: "BLOOD_DONATION",
    location: "Sanana",
    tags: ["SMALL", "FRESH"],
    quantity: 62,
  },
  {
    id: 22,
    description: "Nondisp fx of olecran pro w intartic extn unsp ulna, 7thP",
    type: "BLOOD_DONATION",
    location: "Diriamba",
    tags: ["SUMMER"],
    quantity: 43,
  },
  {
    id: 23,
    description: "Incontinentia pigmenti",
    type: "PROBONO",
    location: "Dakhla",
    tags: ["ADULT", "CANNED"],
    quantity: 45,
  },
  {
    id: 24,
    description: "Partial traumatic transmetacarpal amputation of right hand",
    type: "CLOTHING",
    location: "Trzebinia",
    tags: ["XLARGE", "SUMMER", "MEDICAL"],
    quantity: 76,
  },
  {
    id: 25,
    description: "Other nondisp fx of upper end of unsp humerus, sequela",
    type: "FOOD",
    location: "Balidian",
    tags: ["TYPE_B", "SUMMER"],
    quantity: 15,
  },
  {
    id: 26,
    description: "Military operations involving nuclear weapons",
    type: "FOOD",
    location: "Kaset Sombun",
    tags: ["TYPE_B", "SUMMER"],
    quantity: 55,
  },
  {
    id: 27,
    description: "Osteitis deformans of lower leg",
    type: "MEDICAL_SUPPLIES",
    location: "Huacapampa",
    tags: ["ADULT", "TYPE_B", "SUMMER", "WINTER"],
    quantity: 75,
  },
  {
    id: 28,
    description: "Other vitreous opacities",
    type: "SCHOOL_SUPPLIES",
    location: "Dobšice",
    tags: ["MALE"],
    quantity: 72,
  },
  {
    id: 29,
    description: "Oth injury of blood vessel of right little finger",
    type: "MEDICAL_SUPPLIES",
    location: "Fengle",
    tags: ["MEDIUM", "SMALL", "SUMMER", "LARGE"],
    quantity: 14,
  },
  {
    id: 30,
    description: "Other fracture of third metacarpal bone, right hand, sequela",
    type: "FOOD",
    location: "Schiedam postbusnummers",
    tags: ["SUMMER", "TYPE_A", "XLARGE"],
    quantity: 75,
  },
  {
    id: 31,
    description: "Displacement of int fix of right humerus, init",
    type: "MEDICAL_SUPPLIES",
    location: "Banjar Susut Kaja",
    tags: ["MEDICAL", "TYPE_B"],
    quantity: 40,
  },
  {
    id: 32,
    description: "Adverse effect of antitussives, subsequent encounter",
    type: "BLOOD_DONATION",
    location: "Osypenko",
    tags: ["MALE", "TYPE_B"],
    quantity: 24,
  },
  {
    id: 33,
    description: "Laceration without foreign body, unsp hip, init encntr",
    type: "MEDICAL_SUPPLIES",
    location: "Sława",
    tags: ["TYPE_B", "PAIN_RELIEF", "CHILD", "MALE"],
    quantity: 47,
  },
  {
    id: 34,
    description: "Arthritis due to other bacteria, left ankle and foot",
    type: "SCHOOL_SUPPLIES",
    location: "Campo Largo",
    tags: ["FEMALE", "SUMMER", "LARGE", "MALE"],
    quantity: 10,
  },
  {
    id: 35,
    description: "Oth disrd of amniotic fluid and membrns, third tri, fetus 2",
    type: "CLOTHING",
    location: "Balaka",
    tags: ["MEDIUM", "MALE", "XLARGE"],
    quantity: 39,
  },
  {
    id: 36,
    description: "Unspecified injury of quadriceps muscle, fascia and tendon",
    type: "SCHOOL_SUPPLIES",
    location: "El Cafetal",
    tags: ["CHILD", "WINTER"],
    quantity: 94,
  },
  {
    id: 37,
    description: "Other specified injury of plantar artery of unspecified foot",
    type: "PROBONO",
    location: "Kalinovskoye",
    tags: ["FRESH"],
    quantity: 42,
  },
  {
    id: 38,
    description: "Burn of other internal organ, initial encounter",
    type: "CLOTHING",
    location: "Federal",
    tags: ["CANNED", "TYPE_B"],
    quantity: 70,
  },
  {
    id: 39,
    description: "Poisn by analeptics and opioid receptor antag, slf-hrm, sqla",
    type: "CLOTHING",
    location: "Ol’gino",
    tags: ["MEDICAL", "TYPE_A", "CANNED"],
    quantity: 42,
  },
  {
    id: 40,
    description: "Occup of snowmobile injured in traffic accident, init encntr",
    type: "MEDICAL_SUPPLIES",
    location: "Longhu",
    tags: ["MEDIUM"],
    quantity: 89,
  },
  {
    id: 41,
    description: "Bloodstream infection due to central venous catheter, subs",
    type: "FOOD",
    location: "San Isidro",
    tags: ["ADULT", "FRESH"],
    quantity: 15,
  },
  {
    id: 42,
    description: "Toxic effect of rodenticides, intentional self-harm, sequela",
    type: "PROBONO",
    location: "Kuantan",
    tags: ["MALE", "TYPE_A", "TYPE_B"],
    quantity: 5,
  },
  {
    id: 43,
    description: "Loose body in unspecified finger joint(s)",
    type: "FOOD",
    location: "Ban Thaen",
    tags: ["PAIN_RELIEF"],
    quantity: 13,
  },
  {
    id: 44,
    description: "Unspecified dislocation of left hip, sequela",
    type: "BLOOD_DONATION",
    location: "Itumbiara",
    tags: ["FEMALE", "SUMMER"],
    quantity: 56,
  },
  {
    id: 45,
    description: "Ped w convey injured pick-up truck, pk-up/van, unsp, subs",
    type: "BLOOD_DONATION",
    location: "Ćuprija",
    tags: ["CHILD", "SMALL", "LARGE", "CANNED"],
    quantity: 98,
  },
  {
    id: 46,
    description: "Primary blast injury of sigmoid colon",
    type: "MEDICAL_SUPPLIES",
    location: "Shigou",
    tags: ["WINTER", "XLARGE", "FRESH", "CHILD"],
    quantity: 96,
  },
  {
    id: 47,
    description: "Pnctr w/o fb of unsp lesser toe(s) w/o damage to nail, sqla",
    type: "SCHOOL_SUPPLIES",
    location: "Laotai",
    tags: ["MEDICAL", "TYPE_A", "MALE", "FEMALE"],
    quantity: 45,
  },
  {
    id: 48,
    description: "Milt op w thermal radn effect of nuclear weapon, civ, init",
    type: "FOOD",
    location: "Lisia Góra",
    tags: ["ADULT"],
    quantity: 59,
  },
  {
    id: 49,
    description: "Supervision of other high risk pregnancies, second trimester",
    type: "PROBONO",
    location: "San Juan Nepomuceno",
    tags: ["CHILD", "SUMMER"],
    quantity: 26,
  },
  {
    id: 50,
    description: "Juvenile arthritis, unspecified, knee",
    type: "MEDICAL_SUPPLIES",
    location: "Krajan",
    tags: ["FRESH", "FEMALE", "MEDIUM", "CHILD"],
    quantity: 21,
  },
  {
    id: 51,
    description: "Legal intervnt w unsp sharp objects, bystand injured, subs",
    type: "BLOOD_DONATION",
    location: "Haifa",
    tags: ["ADULT", "WINTER", "FRESH"],
    quantity: 68,
  },
  {
    id: 52,
    description: "Sltr-haris Type II physeal fx upper end of humerus, unsp arm",
    type: "MEDICAL_SUPPLIES",
    location: "Moulay Bouchta",
    tags: ["MALE", "SUMMER", "MEDIUM", "SMALL"],
    quantity: 4,
  },
  {
    id: 53,
    description: "Stenosis due to genitourinary prosth dev/grft, sequela",
    type: "SCHOOL_SUPPLIES",
    location: "Niedzica",
    tags: ["MEDIUM", "WINTER", "CANNED", "ADULT"],
    quantity: 28,
  },
  {
    id: 54,
    description: "Unsp open wound of unsp cheek and temporomandibular area",
    type: "PROBONO",
    location: "Unidad",
    tags: ["CANNED"],
    quantity: 69,
  },
  {
    id: 55,
    description: "Other lesions of median nerve, bilateral upper limbs",
    type: "PROBONO",
    location: "Mełgiew",
    tags: ["FRESH", "SMALL", "SUMMER", "XLARGE"],
    quantity: 19,
  },
  {
    id: 56,
    description: "Laceration without foreign body, left knee, init encntr",
    type: "BLOOD_DONATION",
    location: "Giồng Trôm",
    tags: ["CHILD", "MEDICAL", "MEDIUM", "FEMALE"],
    quantity: 58,
  },
  {
    id: 57,
    description: "Subluxation of distal interphaln joint of l rng fngr, subs",
    type: "CLOTHING",
    location: "Chendian",
    tags: ["WINTER", "MEDIUM", "SUMMER", "FRESH"],
    quantity: 45,
  },
  {
    id: 58,
    description: "Unsp disp fx of first cervcal vert, subs for fx w routn heal",
    type: "PROBONO",
    location: "Međa",
    tags: ["LARGE", "MEDIUM", "MALE"],
    quantity: 6,
  },
  {
    id: 59,
    description: "Other symp and signs w cogn fnctns fol unsp cerebvasc dis",
    type: "FOOD",
    location: "Shuanggang",
    tags: ["SMALL", "MEDICAL"],
    quantity: 79,
  },
  {
    id: 60,
    description: "Type 1 diab w prolif diab rtnop with trctn dtch n-mcla, unsp",
    type: "BLOOD_DONATION",
    location: "Malinta",
    tags: ["CANNED"],
    quantity: 15,
  },
  {
    id: 61,
    description: "Maternal care for oth rhesus isoimmun, first tri, fetus 1",
    type: "SCHOOL_SUPPLIES",
    location: "Huaqiao",
    tags: ["XLARGE", "MEDIUM", "SMALL"],
    quantity: 71,
  },
  {
    id: 62,
    description: "Driver of 3-whl mv inj pk-up truck, pk-up/van nontraf, sqla",
    type: "MEDICAL_SUPPLIES",
    location: "Oslo",
    tags: ["FEMALE"],
    quantity: 15,
  },
  {
    id: 63,
    description: "Pruritus vulvae",
    type: "MEDICAL_SUPPLIES",
    location: "Jabat",
    tags: ["XLARGE", "SMALL", "WINTER"],
    quantity: 85,
  },
  {
    id: 64,
    description: "Lac w/o fb of l bk wl of thorax w/o penet thoracic cavity",
    type: "MEDICAL_SUPPLIES",
    location: "Tallahassee",
    tags: ["CHILD", "SUMMER", "XLARGE", "ADULT"],
    quantity: 70,
  },
  {
    id: 65,
    description: "Asslt by strike agnst or bumped into by another person, sqla",
    type: "MEDICAL_SUPPLIES",
    location: "Zalantun",
    tags: ["XLARGE"],
    quantity: 12,
  },
  {
    id: 66,
    description: "Chronic pain, not elsewhere classified",
    type: "SCHOOL_SUPPLIES",
    location: "Artsvanist",
    tags: ["MALE"],
    quantity: 37,
  },
  {
    id: 67,
    description: "Rieger's anomaly",
    type: "MEDICAL_SUPPLIES",
    location: "Vitry-sur-Seine",
    tags: ["CHILD", "MEDICAL", "FEMALE"],
    quantity: 64,
  },
  {
    id: 68,
    description: "Other superficial bite of hip, right hip, initial encounter",
    type: "CLOTHING",
    location: "Waśniów",
    tags: ["MALE", "SMALL", "XLARGE", "LARGE"],
    quantity: 14,
  },
  {
    id: 69,
    description: "Superficial foreign body of vagina and vulva",
    type: "PROBONO",
    location: "Nancheng",
    tags: ["LARGE", "XLARGE"],
    quantity: 39,
  },
  {
    id: 70,
    description: "Dislocation of T7/T8 thoracic vertebra, sequela",
    type: "FOOD",
    location: "Jiegan",
    tags: ["CANNED", "FRESH"],
    quantity: 32,
  },
  {
    id: 71,
    description: "War op w dest arcrft due to acc deton onboard munit, milt",
    type: "SCHOOL_SUPPLIES",
    location: "Manning",
    tags: ["FEMALE", "XLARGE", "CHILD"],
    quantity: 53,
  },
  {
    id: 72,
    description: "Osteitis condensans, hand",
    type: "MEDICAL_SUPPLIES",
    location: "Sumurgung",
    tags: ["WINTER", "CANNED", "PAIN_RELIEF", "TYPE_B"],
    quantity: 97,
  },
  {
    id: 73,
    description: "Traumatic compartment syndrome of unsp lower extremity",
    type: "CLOTHING",
    location: "Wangchang",
    tags: ["CHILD", "MALE", "SUMMER", "FRESH"],
    quantity: 52,
  },
  {
    id: 74,
    description: "Salter-Harris Type I physeal fracture of phalanx of left toe",
    type: "CLOTHING",
    location: "Dranoc",
    tags: ["ADULT"],
    quantity: 4,
  },
  {
    id: 75,
    description: "Oth nondisp fx of 7th cervcal vert, subs for fx w nonunion",
    type: "MEDICAL_SUPPLIES",
    location: "Quzi",
    tags: ["MEDIUM", "MALE", "TYPE_B", "TYPE_A"],
    quantity: 51,
  },
  {
    id: 76,
    description: "Sprain of unspecified ligament of right ankle, sequela",
    type: "CLOTHING",
    location: "Khadīr",
    tags: ["MALE", "SMALL"],
    quantity: 83,
  },
  {
    id: 77,
    description: "Displaced spiral fracture of shaft of ulna, right arm",
    type: "MEDICAL_SUPPLIES",
    location: "Campo Alegre",
    tags: ["ADULT"],
    quantity: 86,
  },
  {
    id: 78,
    description: "Myositis ossificans traumatica, left forearm",
    type: "SCHOOL_SUPPLIES",
    location: "Mabunga",
    tags: ["MEDICAL"],
    quantity: 80,
  },
  {
    id: 79,
    description: "Burn of unspecified degree of right foot, sequela",
    type: "FOOD",
    location: "Neuss",
    tags: ["FRESH", "TYPE_B", "MALE"],
    quantity: 82,
  },
  {
    id: 80,
    description: "Insect bite (nonvenomous) of unsp forearm, subs encntr",
    type: "FOOD",
    location: "Coxim",
    tags: ["SUMMER", "LARGE", "FRESH"],
    quantity: 58,
  },
  {
    id: 81,
    description: "Unspecified injury of left renal artery, subs encntr",
    type: "CLOTHING",
    location: "Del Campillo",
    tags: ["CHILD"],
    quantity: 53,
  },
  {
    id: 82,
    description: "Corrosions of ear drum",
    type: "SCHOOL_SUPPLIES",
    location: "Minle",
    tags: ["WINTER", "XLARGE"],
    quantity: 88,
  },
  {
    id: 83,
    description: "Poisoning by glucocort/synth analog, intentional self-harm",
    type: "SCHOOL_SUPPLIES",
    location: "Cholpon-Ata",
    tags: ["SUMMER", "ADULT", "LARGE", "FRESH"],
    quantity: 25,
  },
  {
    id: 84,
    description: "Burn due to canoe or kayak on fire",
    type: "CLOTHING",
    location: "Jitian",
    tags: ["PAIN_RELIEF", "TYPE_B", "FEMALE"],
    quantity: 3,
  },
  {
    id: 85,
    description: "Nondisp fx of nk of r rad, 7thN",
    type: "BLOOD_DONATION",
    location: "Jiangshan",
    tags: ["PAIN_RELIEF", "ADULT", "MALE", "FRESH"],
    quantity: 28,
  },
  {
    id: 86,
    description: "Displaced oblique fracture of shaft of unsp radius, init",
    type: "FOOD",
    location: "Książki",
    tags: ["TYPE_B", "PAIN_RELIEF", "SMALL", "TYPE_A"],
    quantity: 58,
  },
  {
    id: 87,
    description: "Other superficial bite of left ear",
    type: "FOOD",
    location: "Taizi",
    tags: ["SMALL", "TYPE_B", "SUMMER"],
    quantity: 91,
  },
  {
    id: 88,
    description: "Varicose veins of lower extremities w ulc and inflammation",
    type: "CLOTHING",
    location: "Xiangxiang",
    tags: ["TYPE_A", "TYPE_B"],
    quantity: 63,
  },
  {
    id: 89,
    description: "Unsp soft tissue disord related to use/pressure, r shoulder",
    type: "CLOTHING",
    location: "Massy",
    tags: ["SUMMER", "XLARGE", "TYPE_A", "PAIN_RELIEF"],
    quantity: 49,
  },
  {
    id: 90,
    description: "Antiphospholipid antibody with hemorrhagic disorder",
    type: "FOOD",
    location: "San José",
    tags: ["WINTER"],
    quantity: 88,
  },
  {
    id: 91,
    description: "Hypertrophy of bone, tibia and fibula",
    type: "PROBONO",
    location: "Gandorhun",
    tags: ["SMALL", "LARGE", "CHILD"],
    quantity: 100,
  },
  {
    id: 92,
    description: "Nondisp fx of l ulna styloid pro, 7thM",
    type: "FOOD",
    location: "Río Tercero",
    tags: ["TYPE_B"],
    quantity: 15,
  },
  {
    id: 93,
    description: "Age-rel osteopor w current path fracture, r low leg, init",
    type: "BLOOD_DONATION",
    location: "Zhifudao",
    tags: ["PAIN_RELIEF", "SMALL", "CHILD", "MALE"],
    quantity: 80,
  },
  {
    id: 94,
    description: "Disp fx of olecran pro w/o intartic extn unsp ulna, 7thG",
    type: "BLOOD_DONATION",
    location: "Pécs",
    tags: ["FEMALE"],
    quantity: 2,
  },
  {
    id: 95,
    description: "Undrdose of selective serotonin reuptake inhibitors, sequela",
    type: "BLOOD_DONATION",
    location: "Daweishan",
    tags: ["SMALL", "PAIN_RELIEF"],
    quantity: 68,
  },
  {
    id: 96,
    description: "Brown-Sequard syndrome of cervical spinal cord",
    type: "FOOD",
    location: "San Isidro",
    tags: ["WINTER"],
    quantity: 11,
  },
  {
    id: 97,
    description: "Pretrm prem ROM, unsp time betw rupt and onset labr, 1st tri",
    type: "CLOTHING",
    location: "Halimaung Jaya (F-3)",
    tags: ["MALE"],
    quantity: 74,
  },
  {
    id: 98,
    description: "Oth physeal fx lower end of r femur, subs for fx w nonunion",
    type: "CLOTHING",
    location: "Ngawen",
    tags: ["CANNED", "TYPE_B"],
    quantity: 7,
  },
  {
    id: 99,
    description: "Chronic superficial gastritis",
    type: "PROBONO",
    location: "Qeshm",
    tags: ["ADULT", "SMALL", "WINTER"],
    quantity: 90,
  },
  {
    id: 100,
    description: "Nondisp seg fx shaft of rad, unsp arm, 7thH",
    type: "FOOD",
    location: "Estância",
    tags: ["MALE"],
    quantity: 35,
  },
];
